export const FILTER_ALL_PIZZA: 'FILTER_ALL_PIZZA' = 'FILTER_ALL_PIZZA';
export const FILTER_MEAT_PIZZA: 'FILTER_MEAT_PIZZA' = 'FILTER_MEAT_PIZZA';
export const FILTER_VEGETARIAN_PIZZA: 'FILTER_VEGETARIAN_PIZZA' = 'FILTER_VEGETARIAN_PIZZA';
export const FILTER_SPICY_PIZZA: 'FILTER_SPICY_PIZZA' = 'FILTER_SPICY_PIZZA';

export const SORT_BY_PRICE: 'SORT_BY_PRICE' = 'SORT_BY_PRICE';
export const SORT_BY_POPULARITY: 'SORT_BY_POPULARITY' = 'SORT_BY_POPULARITY';
export const SORT_BY_ALPHABET: 'SORT_BY_ALPHABET' = 'SORT_BY_ALPHABET';

export const CHANGE_SORTING_MODE: 'CHANGE_SORTING_MODE' = 'CHANGE_SORTING_MODE';

export const ADD_NEW_PIZZA_TO_CART: 'ADD_NEW_PIZZA_TO_CART' = 'ADD_NEW_PIZZA_TO_CART';

export const CLEAR_CART: 'CLEAR_CART' = 'CLEAR_CART';

export const REDUCE_COUNT: 'REDUCE_COUNT' = 'REDUCE_COUNT';
export const INCREASE_COUNT: 'INCREASE_COUNT' = 'INCREASE_COUNT';
export const DELETE_ORDER: 'DELETE_ORDER'= 'DELETE_ORDER';

export const LOAD_CART_STATE: 'LOAD_CART_STATE' = 'LOAD_CART_STATE';